spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/telegram_ai_bot
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

bot:
  name: spring_telegram_ai_bot
  token: ${BOT_TOKEN}

gpt:
  url: "https://api.openai.com/v1/chat/completions"
  token: ${GPT_TOKEN}
  model: "gpt-3.5-turbo"


