spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_URL:jdbc:postgresql://spring-telegram-ai.co7yhuc52rns.eu-central-1.rds.amazonaws.com:5432/spring_telegram_ai}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

bot:
  name: spring_telegram_ai_bot
  token: ${BOT_TOKEN}

gpt:
  url: "https://api.openai.com/v1/chat/completions"
  token: ${GPT_TOKEN}
  model: "gpt-3.5-turbo"

jwt:
  secret: ${JWT_SECRET:413F4428472B4B6250655368566D5970337336763979244226452948404D6351}
  lifetime: ${JWT_LIFETIME:3600000}
  issuer: ${JWT_ISSUER:user_service}

cors:
  allowed:
    origin: ${CORS_ALLOWED_ORIGIN:http://localhost:3000}
