spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/telegram_ai_bot
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

bot:
  name: spring_telegram_ai_bot
  token: "6467352851:AAGa7IFMI0bOghx5MeuRj95Xx1WqMqO2HR0"

gpt:
  url: "https://api.openai.com/v1/chat/completions"
  token: "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"
  model: "gpt-3.5-turbo"


